CROP_SIZE = 512
EXPANSION_FACTOR = 0.8
GUIDANCE_SCALE = 7.5
NUM_INFERENCE_STEPS = 21
STRENGTH = 0.99
INPUT_VIDEO = "video/demo_input.mp4"
OUTPUT_VIDEO = "video/demo_output.mp4"
CROP_PERCENTAGE = 0.5

# Fixed parameters for BIRCH clustering
N_CLUSTERS = 3
BIRCH_THRESHOLD = 0.2
BIRCH_BRANCHING_FACTOR = 20
